# Generated by Django 5.1.4 on 2024-12-06 10:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import timesaver.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_code', models.CharField(editable=False, max_length=7, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_phone_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "999999999". Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')])),
                ('role', models.CharField(choices=[('owner', 'Owner')], default='owner', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=timesaver.models.UploadToPathAndRename('user_images/'))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_code', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Employee ID must start with 3 letters followed by 5 digits.', regex='^[A-Za-z]{3}\\d{5}$')])),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "999999999". Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.TextField()),
                ('role', models.CharField(max_length=50)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=timesaver.models.UploadToPathAndRename('employee_images/'))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_code', models.CharField(editable=False, max_length=7, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('l', 'Liters'), ('g', 'Grams'), ('kg', 'Kilograms'), ('units', 'Units')], default='l', max_length=10)),
                ('product_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='product_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shop_code', models.CharField(editable=False, max_length=7, unique=True)),
                ('shop_name', models.CharField(max_length=255)),
                ('shop_email', models.EmailField(max_length=254, unique=True)),
                ('shop_address', models.CharField(max_length=255)),
                ('shop_phone_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "999999999". Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')])),
                ('shop_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=timesaver.models.UploadToPathAndRename('shop_images/'))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shift_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shift_name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('employees', models.ManyToManyField(to='timesaver.employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesaver.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Online Payment', 'Online Payment')], default='cash', max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesaver.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesaver.shift')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesaver.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profit_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_expenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_of_goods_sold', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('operating_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shortage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesaver.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesaver.shop'),
        ),
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesaver.shop')),
            ],
            options={
                'unique_together': {('name', 'user', 'shop')},
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Online Payment', 'Online Payment')], default='cash', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesaver.expensetype')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesaver.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesaver.shop'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('opening_stock', models.PositiveIntegerField(default=0)),
                ('added_stock', models.PositiveIntegerField(default=0)),
                ('sold_quantity', models.PositiveIntegerField(default=0)),
                ('closing_stock', models.PositiveIntegerField(editable=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='timesaver.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesaver.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
